# Generated by Django 5.2.1 on 2025-08-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_categoria_blog_imagen_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterField(
            model_name='blog',
            name='categoria',
            field=models.CharField(choices=[('recamara', 'Recámara'), ('sala', 'Sala'), ('comedor', 'Comedor'), ('bano', 'Baño')], db_index=True, default='recamara', max_length=30),
        ),
        migrations.AlterField(
            model_name='blog',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
