# Generated by Django 5.2.1 on 2025-06-27 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_direccion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Direccion',
        ),
    ]
