# Generated by Django 5.2.1 on 2025-07-11 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_delete_direccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Casa, Trabajo, etc.', max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('principal', models.BooleanField(default=False)),
                ('calle', models.CharField(max_length=200)),
                ('numero_exterior', models.CharField(blank=True, max_length=20)),
                ('numero_interior', models.CharField(blank=True, max_length=20)),
                ('colonia', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('pais', models.CharField(default='México', max_length=100)),
                ('referencias', models.TextField(blank=True, help_text='Entre calles, puntos de referencia, etc.')),
                ('place_id', models.CharField(blank=True, max_length=255)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dirección de Usuario',
                'verbose_name_plural': 'Direcciones de Usuario',
                'ordering': ['-principal', '-fecha_creacion'],
            },
        ),
    ]
