# Generated by Django 5.2.1 on 2025-07-30 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_perfil_direccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_customer_id', models.CharField(help_text='ID de customer en MercadoPago', max_length=64)),
                ('mp_card_id', models.CharField(help_text='ID de tarjeta en MercadoPago', max_length=64)),
                ('ultimos4', models.CharField(help_text='Últimos 4 dígitos de la tarjeta', max_length=4)),
                ('nombre_tarjeta', models.CharField(help_text='Nombre en la tarjeta', max_length=64)),
                ('marca', models.CharField(help_text='Marca de la tarjeta (Visa, MasterCard, etc.)', max_length=32)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('principal', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'ordering': ['-principal', '-fecha_agregado'],
            },
        ),
    ]
