# Generated by Django 5.2.1 on 2025-06-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='static/ASSETS/productos/default.jpg', upload_to='static/ASSETS/productos/'),
        ),
    ]
