# Generated by Django 5.2.1 on 2025-06-12 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_rename_imagen_producto_imagen_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Stock disponible (mínimo 3, máximo 100)', validators=[django.core.validators.MinValueValidator(3, message='El stock mínimo debe ser de 3 unidades'), django.core.validators.MaxValueValidator(100, message='El stock máximo debe ser de 100 unidades')]),
        ),
    ]
