# Generated by Django 5.2.1 on 2025-06-13 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_remove_pedido_usuario_alter_itemcarrito_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcarrito',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='itemcarrito',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='carrito',
            name='productos',
            field=models.ManyToManyField(through='productos.ItemCarrito', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.carrito'),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productos', models.ManyToManyField(related_name='wishlists', to='productos.producto')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='fecha_actualizado',
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='fecha_agregado',
        ),
    ]
