# Generated by Django 5.2.3 on 2025-06-20 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_alter_itemcarrito_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemcarrito',
            unique_together={('carrito', 'producto')},
        ),
    ]
