# Generated by Django 5.2.1 on 2025-06-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_alter_itemcarrito_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ventas',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de veces que este producto ha sido vendido'),
        ),
    ]
