# Generated by Django 5.2.1 on 2025-07-01 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_producto_ventas'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPromocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('subtitulo', models.CharField(blank=True, max_length=120)),
                ('texto', models.TextField(blank=True)),
                ('imagen_lateral', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('texto_boton', models.CharField(default='Comprar ahora', max_length=50)),
                ('url_boton', models.URLField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('producto_destacado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners_destacados', to='productos.producto')),
                ('productos_carrusel', models.ManyToManyField(blank=True, related_name='banners_carrusel', to='productos.producto')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
