# Generated by Django 5.2.1 on 2025-07-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_bannerpromocional'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerpromocional',
            name='texto_descuento',
            field=models.CharField(default='Hasta 50% de descuento', max_length=80),
        ),
    ]
